# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 朵朵和鹏举的家
description: >- # this means to ignore newlines until "baseurl:"
  房屋使用说明书。
baseurl: "/bay" # the subpath of the site
url: "https://meatbagpro.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: ""

header:
  pages:
    - name: 家 🏠
      slug: /
    - name: 主人 👸
      slug: /owner
    - name: 手册 📖
      slug: /manual

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: hi+duoduo@nai.ba
  follow:
    - type: github
      name: GitHub
      link: http://github.com/naiba
    - type: rss
      name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

future: true

# Used for defeating caching
version: 1
